<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0-windows</TargetFramework>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <AssemblyName>GBFR.InfinityFullAssist</AssemblyName>
    <RootNamespace>GBFR.InfinityFullAssist</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="gbfrelink.utility.manager.Interfaces" Version="1.1.0" />
    <PackageReference Include="NenTools.Reloaded.ScanManager.Interfaces" Version="1.0.0" />
    <PackageReference Include="Reloaded.Memory" Version="9.4.1" />
    <PackageReference Include="Reloaded.Memory.SigScan.ReloadedII.Interfaces" Version="1.2.0" />
    <PackageReference Include="Reloaded.Mod.Interfaces" Version="2.4.0" ExcludeAssets="runtime" />
    <PackageReference Include="Reloaded.SharedLib.Hooks" Version="1.9.0" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="ModConfig.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Signatures\granblue_fantasy_relink_er_2_0_2.ini">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Preview.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
</Project>
